# eugene-doobu: deploy 작업을 제거했습니다.
name: unittest

on:
  push:
    branches:
      - workspace

env:
  # Require unity test
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.2.1f1

  # require Deploy
  SRC_BRANCH: workspace
  WORK_PATH: Packages/${{ github.event.repository.name }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.SRC_BRANCH }}
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: |
            Library-

      # WORK_PATH(=UnityPath)가 변경되면 테스트, 변경되지 않으면 테스트 안함
      - uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            ${{ env.WORK_PATH }}/**/*.cs

      # 예전 버전으로 하면 라이센스 인증이 안됨.. 그래서 동작하는 알파로 변경
      - uses: game-ci/unity-test-runner@v2.0-alpha-4 # https://github.com/marketplace/actions/unity-test-runner
        id: tests
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          unityVersion: ${{ env.UNITY_VERSION }}

      - uses: actions/upload-artifact@v2
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}